//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialAnalytics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RibbonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RibbonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialAnalytics.Resources.RibbonResources", typeof(RibbonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap charts_icon_32x32px {
            get {
                object obj = ResourceManager.GetObject("charts_icon_32x32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Deal_Screener_32x32px {
            get {
                object obj = ResourceManager.GetObject("Deal_Screener_32x32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap history {
            get {
                object obj = ResourceManager.GetObject("history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap history_data {
            get {
                object obj = ResourceManager.GetObject("history_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Home_32x32px {
            get {
                object obj = ResourceManager.GetObject("Home_32x32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap League_Table_32x32px {
            get {
                object obj = ResourceManager.GetObject("League_Table_32x32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login_16x16 {
            get {
                object obj = ResourceManager.GetObject("login_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LogOut_16x16px {
            get {
                object obj = ResourceManager.GetObject("LogOut_16x16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap options_32x32px {
            get {
                object obj = ResourceManager.GetObject("options_32x32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pause_16px {
            get {
                object obj = ResourceManager.GetObject("pause_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play_16px {
            get {
                object obj = ResourceManager.GetObject("play_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Portfolio_32x32px {
            get {
                object obj = ResourceManager.GetObject("Portfolio_32x32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Quotes_32x32px {
            get {
                object obj = ResourceManager.GetObject("Quotes_32x32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Refresh_Button_32x32px {
            get {
                object obj = ResourceManager.GetObject("Refresh_Button_32x32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh_checked_16x16px {
            get {
                object obj = ResourceManager.GetObject("refresh_checked_16x16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Refresh_Mode_Checked {
            get {
                object obj = ResourceManager.GetObject("Refresh_Mode_Checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string Ribbon_AppsGroup_Label {
            get {
                return ResourceManager.GetString("Ribbon_AppsGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Ribbon_Charts_Button {
            get {
                return ResourceManager.GetString("Ribbon_Charts_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Ribbon_DataGroup_Label {
            get {
                return ResourceManager.GetString("Ribbon_DataGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Tools.
        /// </summary>
        public static string Ribbon_DataToolsGroup {
            get {
                return ResourceManager.GetString("Ribbon_DataToolsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Analytics.
        /// </summary>
        public static string Ribbon_FinancialAnalytics_Tab {
            get {
                return ResourceManager.GetString("Ribbon_FinancialAnalytics_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Data.
        /// </summary>
        public static string Ribbon_HistoricalData_Button_Label {
            get {
                return ResourceManager.GetString("Ribbon_HistoricalData_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Ribbon_Home_Button {
            get {
                return ResourceManager.GetString("Ribbon_Home_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Table.
        /// </summary>
        public static string Ribbon_LeagueTable_Label {
            get {
                return ResourceManager.GetString("Ribbon_LeagueTable_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Table.
        /// </summary>
        public static string Ribbon_LeagueTable_Screentip {
            get {
                return ResourceManager.GetString("Ribbon_LeagueTable_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Ribbon_Login_Button_Label {
            get {
                return ResourceManager.GetString("Ribbon_Login_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Ribbon_Logout_Button_Label {
            get {
                return ResourceManager.GetString("Ribbon_Logout_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Ribbon_Options_Button_Label {
            get {
                return ResourceManager.GetString("Ribbon_Options_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Ribbon_Portfolio_Label {
            get {
                return ResourceManager.GetString("Ribbon_Portfolio_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string Ribbon_Quotes_Button_Label {
            get {
                return ResourceManager.GetString("Ribbon_Quotes_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Ribbon_Refresh_ActiveCell {
            get {
                return ResourceManager.GetString("Ribbon_Refresh_ActiveCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook.
        /// </summary>
        public static string Ribbon_Refresh_ActiveWorkbook {
            get {
                return ResourceManager.GetString("Ribbon_Refresh_ActiveWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet.
        /// </summary>
        public static string Ribbon_Refresh_ActiveWorksheet {
            get {
                return ResourceManager.GetString("Ribbon_Refresh_ActiveWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Workbooks.
        /// </summary>
        public static string Ribbon_Refresh_AllWorkbooks {
            get {
                return ResourceManager.GetString("Ribbon_Refresh_AllWorkbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Worksheets.
        /// </summary>
        public static string Ribbon_Refresh_AllWorksheets {
            get {
                return ResourceManager.GetString("Ribbon_Refresh_AllWorksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Ribbon_Refresh_Button {
            get {
                return ResourceManager.GetString("Ribbon_Refresh_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Ribbon_Search_Button_Label {
            get {
                return ResourceManager.GetString("Ribbon_Search_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Ribbon_SettingsGroup_Label {
            get {
                return ResourceManager.GetString("Ribbon_SettingsGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Ribbon_StatusMenu_Connecting {
            get {
                return ResourceManager.GetString("Ribbon_StatusMenu_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Ribbon_StatusMenu_Offline {
            get {
                return ResourceManager.GetString("Ribbon_StatusMenu_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Ribbon_StatusMenu_Online {
            get {
                return ResourceManager.GetString("Ribbon_StatusMenu_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Screener.
        /// </summary>
        public static string Ribbon_StockScreener_Label {
            get {
                return ResourceManager.GetString("Ribbon_StockScreener_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen across Deals universes.
        /// </summary>
        public static string Ribbon_StockScreener_SupertiRibbon_Screener_Supertip {
            get {
                return ResourceManager.GetString("Ribbon_StockScreener_SupertiRibbon_Screener_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Updates.
        /// </summary>
        public static string Ribbon_Update_Paused_Label {
            get {
                return ResourceManager.GetString("Ribbon_Update_Paused_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Updates.
        /// </summary>
        public static string Ribbon_Update_Running_Label {
            get {
                return ResourceManager.GetString("Ribbon_Update_Running_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string Ribbon_Utilities_Label {
            get {
                return ResourceManager.GetString("Ribbon_Utilities_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string Ribbon_Utilities_Menu_Label {
            get {
                return ResourceManager.GetString("Ribbon_Utilities_Menu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Ribbon_Utilities_Shortcuts {
            get {
                return ResourceManager.GetString("Ribbon_Utilities_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Analysis.
        /// </summary>
        public static string Ribbon_VolumeAnalysis {
            get {
                return ResourceManager.GetString("Ribbon_VolumeAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Analysis.
        /// </summary>
        public static string Ribbon_VolumeAnalysis_Screentip {
            get {
                return ResourceManager.GetString("Ribbon_VolumeAnalysis_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xchange Rates.
        /// </summary>
        public static string Ribbon_XchangeRates_Button_Label {
            get {
                return ResourceManager.GetString("Ribbon_XchangeRates_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search_32x32px {
            get {
                object obj = ResourceManager.GetObject("Search_32x32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shortcuts_16x16px {
            get {
                object obj = ResourceManager.GetObject("shortcuts_16x16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap utilities_16x16px {
            get {
                object obj = ResourceManager.GetObject("utilities_16x16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap XchangeRates_16x16px {
            get {
                object obj = ResourceManager.GetObject("XchangeRates_16x16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
