//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialAnalytics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialAnalytics.Resources.ViewsResources", typeof(ViewsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Charts_Window_Title {
            get {
                return ResourceManager.GetString("Charts_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close_icon {
            get {
                object obj = ResourceManager.GetObject("close_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap closeTabButton {
            get {
                object obj = ResourceManager.GetObject("closeTabButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Quotes Data.
        /// </summary>
        public static string HistoricalData_Window_Title {
            get {
                return ResourceManager.GetString("HistoricalData_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_close {
            get {
                object obj = ResourceManager.GetObject("icon_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Table.
        /// </summary>
        public static string LeagueTable_WindowTitle {
            get {
                return ResourceManager.GetString("LeagueTable_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_WindowTitle {
            get {
                return ResourceManager.GetString("Login_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_WindowTitle {
            get {
                return ResourceManager.GetString("Options_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Portfolio_BasicView_Title {
            get {
                return ResourceManager.GetString("Portfolio_BasicView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Portfolio_Create_Button {
            get {
                return ResourceManager.GetString("Portfolio_Create_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed.
        /// </summary>
        public static string Portfolio_DetailedView_Title {
            get {
                return ResourceManager.GetString("Portfolio_DetailedView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundamentals.
        /// </summary>
        public static string Portfolio_FundamentalsView_Title {
            get {
                return ResourceManager.GetString("Portfolio_FundamentalsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Portfolio_PerfomanceView_Title {
            get {
                return ResourceManager.GetString("Portfolio_PerfomanceView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time.
        /// </summary>
        public static string Portfolio_RealTimeView_Title {
            get {
                return ResourceManager.GetString("Portfolio_RealTimeView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for portfolios....
        /// </summary>
        public static string Portfolio_Search_Tip {
            get {
                return ResourceManager.GetString("Portfolio_Search_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio_WindowTitle {
            get {
                return ResourceManager.GetString("Portfolio_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string ProgressDialog_DefaultCaption {
            get {
                return ResourceManager.GetString("ProgressDialog_DefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Details.
        /// </summary>
        public static string ProgressDialog_DefaultTitle {
            get {
                return ResourceManager.GetString("ProgressDialog_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string Qoutes_Window_Title {
            get {
                return ResourceManager.GetString("Qoutes_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up Screen.
        /// </summary>
        public static string ScreenBuilderViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ScreenBuilderViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Screener.
        /// </summary>
        public static string Screener_WindowTitle {
            get {
                return ResourceManager.GetString("Screener_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Results.
        /// </summary>
        public static string ScreenResultsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ScreenResultsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_WindowTitle {
            get {
                return ResourceManager.GetString("Search_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xchange Rates.
        /// </summary>
        public static string XchangeRates_Window_Title {
            get {
                return ResourceManager.GetString("XchangeRates_Window_Title", resourceCulture);
            }
        }
    }
}
