//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialAnalytics.Wrappers.Excel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialAnalytics.Wrappers.Excel.Resources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string AxisCrosses_Automatic {
            get {
                return ResourceManager.GetString("AxisCrosses_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string AxisCrosses_Custom {
            get {
                return ResourceManager.GetString("AxisCrosses_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string AxisCrosses_Maximum {
            get {
                return ResourceManager.GetString("AxisCrosses_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string AxisCrosses_Minimum {
            get {
                return ResourceManager.GetString("AxisCrosses_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairline.
        /// </summary>
        public static string BorderWeight_Hairline {
            get {
                return ResourceManager.GetString("BorderWeight_Hairline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string BorderWeight_Medium {
            get {
                return ResourceManager.GetString("BorderWeight_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string BorderWeight_None {
            get {
                return ResourceManager.GetString("BorderWeight_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thick.
        /// </summary>
        public static string BorderWeight_Thick {
            get {
                return ResourceManager.GetString("BorderWeight_Thick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin.
        /// </summary>
        public static string BorderWeight_Thin {
            get {
                return ResourceManager.GetString("BorderWeight_Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string HorizontalAlignment_Center {
            get {
                return ResourceManager.GetString("HorizontalAlignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Across Selection.
        /// </summary>
        public static string HorizontalAlignment_CenterAcrossSelection {
            get {
                return ResourceManager.GetString("HorizontalAlignment_CenterAcrossSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed.
        /// </summary>
        public static string HorizontalAlignment_Distributed {
            get {
                return ResourceManager.GetString("HorizontalAlignment_Distributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string HorizontalAlignment_Fill {
            get {
                return ResourceManager.GetString("HorizontalAlignment_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string HorizontalAlignment_General {
            get {
                return ResourceManager.GetString("HorizontalAlignment_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        public static string HorizontalAlignment_Justify {
            get {
                return ResourceManager.GetString("HorizontalAlignment_Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string HorizontalAlignment_Left {
            get {
                return ResourceManager.GetString("HorizontalAlignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string HorizontalAlignment_Right {
            get {
                return ResourceManager.GetString("HorizontalAlignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string LegendPosition_LegendPositionBottom {
            get {
                return ResourceManager.GetString("LegendPosition_LegendPositionBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string LegendPosition_LegendPositionCorner {
            get {
                return ResourceManager.GetString("LegendPosition_LegendPositionCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string LegendPosition_LegendPositionCustom {
            get {
                return ResourceManager.GetString("LegendPosition_LegendPositionCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LegendPosition_LegendPositionLeft {
            get {
                return ResourceManager.GetString("LegendPosition_LegendPositionLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string LegendPosition_LegendPositionRight {
            get {
                return ResourceManager.GetString("LegendPosition_LegendPositionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string LegendPosition_LegendPositionTop {
            get {
                return ResourceManager.GetString("LegendPosition_LegendPositionTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        public static string LineStyle_Continuous {
            get {
                return ResourceManager.GetString("LineStyle_Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash.
        /// </summary>
        public static string LineStyle_Dash {
            get {
                return ResourceManager.GetString("LineStyle_Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Dot.
        /// </summary>
        public static string LineStyle_DashDot {
            get {
                return ResourceManager.GetString("LineStyle_DashDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Dot Dot.
        /// </summary>
        public static string LineStyle_DashDotDot {
            get {
                return ResourceManager.GetString("LineStyle_DashDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot.
        /// </summary>
        public static string LineStyle_Dot {
            get {
                return ResourceManager.GetString("LineStyle_Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        public static string LineStyle_Double {
            get {
                return ResourceManager.GetString("LineStyle_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LineStyle_LineStyleNone {
            get {
                return ResourceManager.GetString("LineStyle_LineStyleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slant Dash Dot.
        /// </summary>
        public static string LineStyle_SlantDashDot {
            get {
                return ResourceManager.GetString("LineStyle_SlantDashDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string TickLabelPosition_High {
            get {
                return ResourceManager.GetString("TickLabelPosition_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string TickLabelPosition_Low {
            get {
                return ResourceManager.GetString("TickLabelPosition_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next To Axis.
        /// </summary>
        public static string TickLabelPosition_NextToAxis {
            get {
                return ResourceManager.GetString("TickLabelPosition_NextToAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TickLabelPosition_None {
            get {
                return ResourceManager.GetString("TickLabelPosition_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TickLabelPosition_Undefined {
            get {
                return ResourceManager.GetString("TickLabelPosition_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        public static string UnderlineStyle_UnderlineStyleDouble {
            get {
                return ResourceManager.GetString("UnderlineStyle_UnderlineStyleDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string UnderlineStyle_UnderlineStyleDoubleAccounting {
            get {
                return ResourceManager.GetString("UnderlineStyle_UnderlineStyleDoubleAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string UnderlineStyle_UnderlineStyleNone {
            get {
                return ResourceManager.GetString("UnderlineStyle_UnderlineStyleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string UnderlineStyle_UnderlineStyleSingle {
            get {
                return ResourceManager.GetString("UnderlineStyle_UnderlineStyleSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string UnderlineStyle_UnderlineStyleSingleAccounting {
            get {
                return ResourceManager.GetString("UnderlineStyle_UnderlineStyleSingleAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string VerticalAlignment_Bottom {
            get {
                return ResourceManager.GetString("VerticalAlignment_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string VerticalAlignment_Center {
            get {
                return ResourceManager.GetString("VerticalAlignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed.
        /// </summary>
        public static string VerticalAlignment_Distributed {
            get {
                return ResourceManager.GetString("VerticalAlignment_Distributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        public static string VerticalAlignment_Justify {
            get {
                return ResourceManager.GetString("VerticalAlignment_Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string VerticalAlignment_Top {
            get {
                return ResourceManager.GetString("VerticalAlignment_Top", resourceCulture);
            }
        }
    }
}
